name: Weekly Sunday Report

on:
  schedule:
    # This is "Cron" format for Sunday at 08:00 AM UTC
    - cron: '0 8 * * 0'
  workflow_dispatch: # This allows you to also trigger it from GitHub manually

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Report Script
        env:
          DB_URL: ${{ secrets.DB_URL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python send_automated_report.py
